@startuml
partition "Отправка посылки" {
  start
  :Авторизация пользователя/
  if (Пользователь зарегестрирован?) then (да)
    :Выполнить вход]
  else (нет)
    :Создать новую запись]
  endif
  :Ввод данных посылки/
  :Подтвердить отправку поссылки]
  stop
}

partition "Просмотр статуса посылки" {
  start
  :Авторизация пользователя/
  if (Пользователь зарегестрирован?) then (да)
    :Выполнить вход]
  else (нет)
    :Создать новую запись]
  endif
  :Ввод данных посылки/
  if (Данные посылки есть в базе?) then (да)
      :вывести статус посылки]
    else (нет)
      :посылка не найдена]
      endif
  stop
}

partition "Изменение статуса посылки администратором" {
  start
  :Авторизация администратора/
  :Ввод данных посылки/
    while (Данные посылки есть в базе?) is (нет)
    :посылка не найдена]
    endwhile (да)
     :Изменение статуса посылки]
  stop
  }
  partition "Удаление пользователя/посылки" {
    start
    :Авторизация администратора/
    :Ввод данных пользователя/посылки/
      while (Данные есть в базе?) is (нет)
      :id не найден]
      endwhile (да)
       :Удаление]

    stop
}
@enduml