@startuml
partition "Отправка посылки" {
  start
  :Авторизация пользователя/
  if (Пользователь зарегестрирован?) then (да)
    :Выполнить вход]
  else (нет)
    :Создать новую запись]
  endif
  :Ввод данных посылки/
  :Подтвердить отправку поссылки]
  stop
}

partition "Просмотр статуса посылки" {
  start
  :Авторизация пользователя/
  if (Пользователь зарегестрирован?) then (да)
    :Выполнить вход]
  else (нет)
    :Создать новую запись]
  endif
  :Ввод данных посылки/
  if (Данные посылки есть в базе?) then (да)
      :вывести статус посылки]
    else (нет)
      :посылка не найдена]
      endif
  stop
}

partition "Выдача посылки администратором" {
  start
  :Авторизация администратора/
  :Ввод данных посылки/
    while (Данные посылки есть в базе?) is (нет)
    :посылка не найдена]
    endwhile (да)
     :Изменение статуса посылки]
  if (Посылка доставлена?) then (да)
    :Изменение статуса посылки на "Готова к выдаче"]
    :Отправка уведомления о "Готова к выдаче"]
  else (нет)
    :Изменение статуса посылки на "Не готова к выдаче"]
    :Отправка уведомления о "Не готова к выдаче"]
  endif
  :Формирование отчета]
  stop
}
@enduml