@startuml
left to right direction
skinparam packageStyle rectangle
actor "Администратор2" as User1
package "Система посылок" {
    usecase "Регистрация посылок" as UC_RegisterOf
    usecase "Создание записей" as UC_Creation
    usecase "Выдача посылок" as UC_issuance
    usecase "Архивирование записей о доставке" as UC_report
    usecase "поиск посылок" as UC_search
    usecase "изменение статуса посылки с отображением в бд" as UC_status
    usecase "Авторизация" as UC_Register
}
actor "Пользователь" as User2
User1 -- UC_issuance
User1 -- UC_report
User1 -- UC_search
User1 -- UC_status
User2 -- UC_Register
UC_Register -- UC_Creation
UC_Register -- UC_search
UC_Register -- UC_RegisterOf
@enduml
