@startuml
start
:ввести запрос]
:ввод данных посылки/пользователя/
while (Проверка данных посылки или пользователя) is (не прошла)
:ввод данных посылки/пользователя/
endwhile (прошла)
:создание записей]
:отправка уведомления/
stop
@enduml